# -*- mode: org ; mode: visual-line; coding: utf-8 -*- -*
* What is ErZauker?

Er Zauker is an erlang-based search engine for programming languages. 
Er Zauker is based from ideas taken by old Google Code Search and uses Redis as storage engine.
It is a different implementation of the Code Zauker project.


* How to build
make 
* How to try (indexing its own code)
#+BEGIN_SRC shell
 make test-indexer
#+END_SRC

* Giovanni Giorgi Erlang Redis Study project 			       :spec:
This project is a Clone of Code Zauker Code indexer.
It is written in Erlang, as a Testing Platform.

Please take a look to
 https://github.com/daitangio/code_zauker
for more informations


* How to develop: suggested installation
** On Linux (Debian jessie)
Erlang R17 is needed. We strongly suggest Hipe (native compiler) on a 64bit installation
Install Erlang Hipe and dev libs (use "aptitude versions" to get the complete list).
On Debian the R17 is available only under 'testing' branch (i.e. 1:17.1-dfsg-3)

The minimum required sets depends on your distribution. On Debian try:

With aptitude
#+BEGIN_SRC shell
i   erlang-base-hipe                - Erlang/OTP HiPE enabled virtual machine an
i   erlang-debugger                 - Erlang/OTP application for debugging and t
i   erlang-dev                      - Erlang/OTP development libraries and heade
i   erlang-eunit                    - Erlang/OTP module for unit testing        
i   erlang-snmp                     - Erlang/OTP SNMP applications              
i   erlang-ssh                      - Erlang/OTP implementation of SSH protocol 
i   erlang-syntax-tools             - Erlang/OTP modules for handling abstract E
i   erlang-test-server              - Erlang/OTP server for automated applicatio
i   erlang-xmerl                    - Erlang/OTP XML tools                      
#+END_SRC

Complete list (via =dpkg --get-selections | grep erlang=):

| Package name         | Suggested version |
| erlang-asn1          | 1:17.1-dfsg-3     |
| erlang-base-hipe     |                   |
| erlang-crypto        |                   |
| erlang-debugger      |                   |
| erlang-dev           |                   |
| erlang-et            |                   |
| erlang-eunit         |                   |
| erlang-gs            |                   |
| erlang-inets         |                   |
| erlang-mnesia        |                   |
| erlang-observer      |                   |
| erlang-public-key    |                   |
| erlang-runtime-tools |                   |
| erlang-snmp          |                   |
| erlang-ssh           |                   |
| erlang-ssl           |                   |
| erlang-syntax-tools  |                   |
| erlang-test-server   |                   |
| erlang-tools         |                   |
| erlang-webtool       |                   |
| erlang-wx            |                   |
| erlang-xmerl         |                   |
| erlang-syntax-tools  |                   |
